XTENDED_BUILD_TYPE := OFFICIAL
XTENDED_BUILD_MAINTAINER := Rahul‎Pal‎XDA
TARGET_USES_BLUR := false
TARGET_FACE_UNLOCK_SUPPORTED := true
TARGET_SUPPORTS_QUICK_TAP := true
TARGET_BOOT_ANIMATION_RES := 1080
